# Generated by Django 5.1.2 on 2024-11-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=10)),
                ('educacion', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('comentarios', models.TextField()),
                ('terminos', models.BooleanField()),
            ],
        ),
    ]
