# Generated by Django 5.1.2 on 2024-11-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='educacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
